# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_auto_20190511_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.TextField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Category')),
                ('image_location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
